import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Brown Brim",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    originalPrice: 250,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 1,
  },
  {
    _id: uuid(),
    name: "Blue Beanie",
    imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    originalPrice: 180,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Brown Cowboy",
    imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    originalPrice: 350,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 1,
  },
  {
    _id: uuid(),
    name: "Grey Brim",
    imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
    originalPrice: 250,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Green Beanie",
    imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
    originalPrice: 180,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Palm Tree Cap",
    imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
    originalPrice: 140,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Red Beanie",
    imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
    originalPrice: 180,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "Wolf Cap",
    imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
    originalPrice: 140,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 2,
  },
  {
    _id: uuid(),
    name: "Blue Snapback",
    imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
    originalPrice: 160,
    categoryName: "Hats",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Adidas NMD",
    imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    originalPrice: 2200,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Adidas Yeezy",
    imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
    originalPrice: 2800,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Black Converse",
    imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
    originalPrice: 1100,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "Nike White AirForce",
    imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    originalPrice: 1600,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Nike Red High Tops",
    imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
    originalPrice: 1600,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 2,
  },
  {
    _id: uuid(),
    name: "Nike Brown High Tops",
    imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
    originalPrice: 1600,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Air Jordan Limited",
    imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    originalPrice: 1900,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Timberlands",
    imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    originalPrice: 2000,
    categoryName: "Sneakers",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Black Jean Shearling",
    imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    originalPrice: 1250,
    categoryName: "Jackets",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Blue Jean Jacket",
    imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    originalPrice: 900,
    categoryName: "Jackets",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Grey Jean Jacket",
    imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    originalPrice: 900,
    categoryName: "Jackets",
    discount_percent: 10,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "Brown Shearling",
    imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    originalPrice: 1650,
    categoryName: "Jackets",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Tan Trench",
    imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    originalPrice: 1850,
    categoryName: "Jackets",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Blue Tanktop",
    imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    originalPrice: 2500,
    categoryName: "Womens",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Floral Blouse",
    imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    originalPrice: 2000,
    categoryName: "Women",
    discount_percent: 10,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "Floral Dress",
    imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    originalPrice: 8000,
    categoryName: "Women",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Red Dots Dress",
    imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    originalPrice: 8000,
    categoryName: "Women",
    discount_percent: 10,
    rating: 2,
  },
  {
    _id: uuid(),
    name: "Striped Sweater",
    imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    originalPrice: 4500,
    categoryName: "Women",
    discount_percent: 10,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Yellow Track Suit",
    imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    originalPrice: 1350,
    categoryName: "Women",
    discount_percent: 20,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "White Blouse",
    imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
    originalPrice: 2000,
    categoryName: "Women",
    discount_percent: 10,
    rating: 1,
  },
  {
    _id: uuid(),
    name: "Camo Down Vest",
    imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
    originalPrice: 3250,
    categoryName: "Mens",
    discount_percent: 25,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Floral T-shirt",
    imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
    originalPrice: 2000,
    categoryName: "Mens",
    discount_percent: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Black & White Longsleeve",
    imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
    originalPrice: 2500,
    categoryName: "Mens",
    discount_percent: 13,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "Pink T-shirt",
    imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
    originalPrice: 2500,
    categoryName: "Mens",
    discount_percent: 15,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Jean Long Sleeve",
    imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
    originalPrice: 4000,
    discount_percent: 10,
    categoryName: "Mens",
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Burgundy T-shirt",
    imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
    originalPrice: 2500,
    categoryName: "Mens",
    discount_percent: 10,
    rating: 4,
  },
];
